# Generated by Django 4.1.5 on 2023-01-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_post_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=1, verbose_name='Лайк'),
            preserve_default=False,
        ),
    ]
