# Generated by Django 4.1.5 on 2023-01-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_post_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='Лайк'),
        ),
    ]
